spring.application.name=fullstack3

server.port=8081

##LOGGING
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG
logging.level.java.sql=DEBUG

## CONEXION CON WALLET
spring.datasource.url=jdbc:oracle:thin:@NOMBREWALLET_tp?TNS_ADMIN=./Wallet_NOMBREWALLET
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
# NO REALIZA NINGUN CAMBIO EN LA BBDD
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000